rollout_length: 64
rollout_length_history_size: 50
callbacks:
  - progress_bar
  - keyboard_interrupt
  - adaptive_learning_rate:
      monitor: "*/approx_kl"
      allowed_range: [0.005, 0.1]
      factor: 0.5
  - checkpoint:
      save_iter_interval: 25
  - logging
  - tensorboard:
      step_log_interval: 10
      histogram_step_interval: 10000
      initial_load_timeout: 1200
      max_reload_threads: 4
      step_metrics:
        "reward": [value]
        "reward/*": [mean]
        "termination/*": [mean]
        "command/*": [histogram]
        "curriculum/*": [histogram]
#   - early_stopping:
#       monitor: "*/loss"
#       mode: min
#       max_no_improve_iters: 20
#       min_delta: 0.0
playback:
  - target: "command/lin_vel_x"
    measured: "state/base_lin_vel_body[0]"
    label: "X linear velocity (m/s)"
    limits: [-2.8, 2.8]
  - target: "command/lin_vel_y"
    measured: "state/base_lin_vel_body[1]"
    label: "Y linear velocity (m/s)"
    limits: [-0.8, 0.8]
  - target: "command/ang_vel_z"
    measured: "state/base_ang_vel_body[2]"
    label: "Z angular velocity (rad/s)"
    limits: [-2.0, 2.0]
    