rollout_length: 64
rollout_length_history_size: 50
callbacks:
  - progress_bar
  - adaptive_learning_rate:
      monitor: "*/approx_kl"
      allowed_range: [0.01, 0.3]
      factor: 0.5
  - checkpoint:
      save_interval: 100
  - logging
  - tensorboard:
      histogram_log_interval: 500
      step_metrics:
        "reward": [value]
        "reward/*": [mean]
        "termination/*": [mean]
        "command/*": [histogram]
        "observation/*": [histogram]
        "curriculum/*": [histogram]
#   - early_stopping: 
#       monitor: "*/loss"
#       mode: min
#       max_no_improve_iters: 20
#       min_delta: 0.0
