action_manager_config:
  terms:
    hard_clamp: {min_value: -1.0, max_value: 1.0}
    linear_map: {}


command_manager_config:
  terms:
    lin_vel_x: {type: UniformOnReset, params: {min_value: -0.5, max_value: 0.5}}
    lin_vel_y: {type: UniformOnReset, params: {min_value: -0.5, max_value: 0.5}}
    ang_vel_z: {type: UniformOnReset, params: {min_value: -1.0, max_value: 1.0}}
  constraints:
    ang_vel_z: {operator: "<=", expression: "0.5 * (1.0 - abs({lin_vel_x}))"}


observation_manager_config:
  clip: 100.0
  terms:
    base_angular_velocity: {scale: 0.25}
    projected_gravity: {scale: 1.0}
    command: {scale: 1.0}
    joint_position: {scale: 1.0}
    joint_velocity: {scale: 0.05}
    last_action: {scale: 1.0}


reward_manager_config:
  terms:
    # action_diff_l2: {weight: 1.0, params: {sigma: 0.25}}
    action_diff_l2: {weight: 1.0}


termination_manager_config:
  type: LocomotionTerminationManager
  config:
    terms:
      illegal_contact:
        enabled: true

      base_height:
        enabled: true
        min_height: 0.20

      episode_timeout:
        enabled: true
        max_episode_steps: 1000


curriculum_manager_config:
  type: LocomotionCurriculumManager
  config:
    enabled: true

    terms:
      command_range:
        type: CommandRangeCurriculum

      terrain_level:
        type: TerrainCurriculum


event_manager_config:


randomization_manager_config:
