constants:
  base_target_height: &base_target_height 0.27
  foot_lifted_height: &foot_lifted_height 0.08


action_manager_config:
  terms:
    hard_clamp: {min_value: -1.0, max_value: 1.0}
    linear_map: {}


command_manager_config:
  terms:
    lin_vel_x: {type: LpacSampleOnReset, params: {group: locomotion, min_value: 0.0, max_value: 0.5, num_bins: 3, noise_scale: 0.167}}
    lin_vel_y: {type: LpacSampleOnReset, params: {group: locomotion, min_value: -0.1, max_value: 0.1, num_bins: 3, noise_scale: 0.167}}
    ang_vel_z: {type: LpacSampleOnReset, params: {group: locomotion, min_value: -0.3, max_value: 0.3, num_bins: 3, noise_scale: 0.167}}
    half_period_duration: {type: LpacSampleOnReset, params: {group: duration, min_value: 0.1, max_value: 1.0, num_bins: 10, noise_scale: 0.167}}
    foot_phase_real: {type: LpacSampleOnReset, params: {group: phase, dim: 4, min_value: -1.0, max_value: 1.0, num_bins: 3, noise_scale: 0.167}}
    foot_phase_imag: {type: LpacSampleOnReset, params: {group: phase, dim: 4, min_value: -1.0, max_value: 1.0, num_bins: 3, noise_scale: 0.167}}

  constraints:
    foot_phase_real:
      operator: "!="
      expression: "torch.where({foot_phase_imag} == 0.0, torch.zeros_like({foot_phase_real}), torch.full_like({foot_phase_real}, torch.nan))"


observation_manager_config:
  clip: 3.0
  terms:
    base_angular_velocity: {scale: 0.05}
    projected_gravity: {scale: 1.0}
    command: {scale: 0.5}
    joint_position: {scale: 0.3}
    joint_velocity: {scale: 0.05}
    last_action: {scale: 0.1}
    second_last_action: {scale: 0.1}


reward_manager_config:
  terms:
    illegal_contact_l1: {weight: -1.0}
    track_linear_velocity_xy_l2_exp_and_logcosh: {weight: 5.0, params: {logcosh_weight: 0.1}}
    track_angular_velocity_z_l2_exp_and_logcosh: {weight: 5.0, params: {logcosh_weight: 0.1, std: 2.5}}
    track_linear_velocity_xy_error_integral_l2: {weight: -1.0e-3, params: {integral_length: 25}}
    track_angular_velocity_z_error_integral_l2: {weight: -1.0e-3, params: {integral_length: 25}}
    base_linear_velocity_z_l2: {weight: -2.0}
    base_height_l2: {weight: -5.0, params: {target_height: *base_target_height}}
    base_angular_velocity_xy_l2: {weight: -0.01}
    projected_gravity_xy_l2: {weight: -5.0}
    action_diff_l2: {weight: -0.05}
    joint_velocity_l2: {weight: -0.001}
    joint_position_l2: {weight: -0.05}
    joint_limit_violation_l1: {weight: -5.0}
    joint_power_l1: {weight: -2.0e-5}
    quadrupedal_gait_phase_l2_exp: {weight: 2.0, params: {target_height: *base_target_height}}
    quadrupedal_foot_velocity_diff_l2: {weight: -0.05}
    foot_state_duration_command_weighed_exp: {weight: 1.0, params: {sigma: 0.5}}
    foot_sliding_velocity_l2: {weight: -0.01}
    foot_lift_height_velocity_weighted_exp: {weight: 0.05, params: {target_height: *foot_lifted_height}}
    foot_contact_without_command: {weight: 0.5}


termination_manager_config:
  terms:
    body_contact: {body_names: [trunk, FR_thigh, FL_thigh, RR_thigh, RL_thigh]}


curriculum_manager_config:
  terms:
    lpac_command_reward: {max_cells: 100000}


event_manager_config:


randomization_manager_config:
