constants:
  base_target_height: &base_target_height 0.2
  foot_lifted_height: &foot_lifted_height 0.1
  integral_length: &integral_length 200
  action_lags: &action_lags 3


action_manager_config:
  terms:
    tanh_map: {}
    keyframe_centered_linear_map: {}


command_manager_config:
  terms:
    lin_vel_x: {type: UniformOnReset, params: {min_value: 0.0, max_value: 0.0}}
    lin_vel_y: {type: UniformOnReset, params: {min_value: 0.0, max_value: 0.0}}
    ang_vel_z: {type: UniformOnReset, params: {min_value: 0.0, max_value: 0.0}}


observation_manager_config:
  clip: 3.0
  terms:
    base_linear_velocity: {scale: 0.5}
    base_angular_velocity: {scale: 0.05}
    base_height: {scale: 2.0}
    projected_gravity: {scale: 1.0}
    command: {scale: 0.5}
    joint_position: {scale: 0.3}
    joint_position_diff: {scale: 0.5}
    joint_velocity: {scale: 0.05}
    foot_duration_tanh: {scale: 1.0}
    foot_contact_state: {scale: 1.0}
    foot_height: {scale: 3.0}
    last_action: {scale: 0.1, lags: *action_lags}
    track_linear_velocity_x_error_integral_tanh: {scale: 1.0, integral_length: *integral_length}
    track_linear_velocity_y_error_integral_tanh: {scale: 1.0, integral_length: *integral_length}
    track_angular_velocity_z_error_integral_tanh: {scale: 1.0, integral_length: *integral_length}


reward_manager_config:
  terms:
    track_linear_velocity_x_l2_exp_and_logcosh: {weight: 2.0, params: {logcosh_weight: 0.1}}
    track_linear_velocity_y_l2_exp_and_logcosh: {weight: 2.0, params: {logcosh_weight: 0.1}}
    track_angular_velocity_z_l2_exp_and_logcosh: {weight: 1.0, params: {logcosh_weight: 0.1, std: 2.5}}
    track_linear_velocity_x_error_integral_l2: {weight: -2.0, params: {integral_length: *integral_length}}
    track_linear_velocity_y_error_integral_l2: {weight: -2.0, params: {integral_length: *integral_length}}
    track_angular_velocity_z_error_integral_l2: {weight: -1.0, params: {integral_length: *integral_length}}
    
    base_height_l2: {weight: -0.5, params: {target_height: *base_target_height, std: 0.2}}
    base_linear_velocity_z_l2: {weight: -1.0}
    # base_angular_velocity_xy_l2: {weight: -1.0}
    projected_gravity_xy_l2: {weight: -2.0}

    action_diff_l2: {weight: -0.2, params: {max_lag: *action_lags}}

    joint_velocity_l2: {weight: -0.02}
    joint_position_diff_l2: {weight: -5.0}
    joint_limit_violation_l1: {weight: -5.0}
    joint_power_l1: {weight: -2.0e-4}

    illegal_contact_l1: {weight: -2.0}

    trot_loop_duration_tanh: {weight: 5.0, params: {growth_rate: 5.0}}
    # quadrupedal_foot_velocity_diff_l2: {weight: -1.0}
    foot_state_switch: {weight: -1.0}
    foot_state_duration_cubic_command_weighed_exp: {weight: 0.2, params: {sigma: 0.5}}
    foot_sliding_velocity_l2: {weight: -1.0}
    foot_contact_without_command: {weight: 2.0}
    foot_lift_height_diff_command_gated_l2: {weight: -1.0, params: {target_height: *foot_lifted_height}}


termination_manager_config:
  terms:
    body_contact: {body_names: [trunk]}


curriculum_manager_config:
  terms: {}


event_manager_config: {}
randomization_manager_config: {}
