runtime:
  device: cuda
  dtype: float32
  num_threads: 4
  seed: null
  deterministic_ops: false

logging:
  file_name: training.log
  console: true


stage:
  - standing:
      max_iterations: 100
      transition:
        - {metric: "rollout/mean_len", method: mean, operator: ">=", threshold: 900.0, window: 5}

  - velocity_tracking:
      max_iterations: 1500
      transition:
        - {metric: "reward/track_linear_velocity_xy_l2_exp_and_logcosh", method: mean, operator: ">=", threshold: 4.5, window: 25}
        - {metric: "reward/track_angular_velocity_z_l2_exp_and_logcosh", method: mean, operator: ">=", threshold: 1.8, window: 25}
        - {metric: "rollout/mean_len", method: mean, operator: ">=", threshold: 900.0, window: 25}


component:
  runner:
    - type: on_policy
      config: isaac_rollout_64

  algorithm:
    - type: ppo
      config: ppo_num_batch_32

  policy:
    - type: actor_critic
      config: actor_critic_direct_actuation

  environment:
    - type: vector_env
      config: vector_env_1024

  simulator:
    - type: isaac_sim
      config: isaac_sim_unitree_go1_rgb_array

  task:
    - type: locomotion
      config: locomotion_unitree_go1_standing
    - type: locomotion
      config: locomotion_unitree_go1_velocity
