runtime:
  device: cuda
  dtype: float32
  num_threads: 4
  seed: None
  deterministic: true


stage:

  - mean_reward:
      operator: ">="
      threshold: 10.0
      window: 100

  - mean_reward:
      operator: ">="
      threshold: 100.0
      window: 100


component:

  runner:
    - type: "on_policy"
      config: "rl_unitree_go1"

  algorithm:
    - type: "ppo"
      config: "ppo_unitree_go1_stage1"

  model:
    - type: ""
      config: "tmp"

  environment:
    - type: "vector_env"
      config: "vector_env_1_unitree_go1"
      
  simulator:
    - type: "mujoco"
      config: "mujoco_unitree_go1_stage1"
      
  task:
    - type: "locomotion"
      config: "locomotion_unitree_go1"
