runtime:
  device: cuda
  dtype: float32
  num_threads: 4
  seed: None
  deterministic: true


runner:
  runner_type: "on_policy"
  max_iterations: 2000
  rollout_length: 48
  stage_manager: "stage_unitree_go1"
  callback_names:
    - progress_bar
    - checkpoint
    - tensorboard
    - early_stopping
    - logging


component:

  algorithm:
    type_name: "ppo"
    config_names:
      - "ppo_unitree_go1_stage1"

  model:
    type_name: ""
    config_names:
      - "tmp"

  environment:
    type_name: "vector_env"
    config_names:
      - "mujoco_unitree_go1_stage1"
      
  simulator:
    type_name: ""
    config_names:
      - "tmp"
      
  task:
    type_name: ""
    config_names:
      - "tmp"



