runtime:
  device: cuda
  dtype: float32
  num_threads: 4
  seed: None
  deterministic: true


component:

  runner:
    - type: "on_policy"
      config: "rl_unitree_go1"

  algorithm:
    - type: "ppo"
      config: "ppo_unitree_go1_stage1"

  model:
    - type: ""
      config: "tmp"
    - type: ""
      config: "tmp2"

  environment:
    - type: "vector_env"
      config: "mujoco_unitree_go1_stage1"
      
  simulator:
    - type: ""
      config: "tmp"
      
  task:
    - type: ""
      config: "tmp"



