model_path: .\assets\unitree_go1\MJCF\scene.xml
sim_dt: 0.002
frame_skip: 10
render_mode: human
foot_geom_names: [FR, FL, RR, RL]
floor_geom_names: [floor]
foot_contact_force_threshold: 15.0
reset_keyframe: "home"
